repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    - id: isort

